import type { DatabaseConnectorFactory } from "@zeruxjs/db";
import { createSqlConnector } from "../../db-sql-core/dist/index.js";

type PgQueryResult = unknown;

type PgPoolLike = {
    query(statement: string, params?: unknown[]): Promise<PgQueryResult>;
    end?(): Promise<void>;
};

interface PgConnectorOptions extends Record<string, unknown> {
    client?: {
        query?: (statement: string, params?: unknown[]) => Promise<unknown>;
        execute?: (statement: string, params?: unknown[]) => Promise<unknown>;
    };
    pool?: PgPoolLike;
    host?: string;
    hostname?: string;
    username?: string;
    user?: string;
    password?: string;
    database?: string;
    port?: number;
    ssl?: unknown;
    max?: number;
    connectionString?: string;
    executor?: (statement: string, params: unknown[]) => Promise<unknown> | unknown;
}

/**
 * Title: PostgreSQL pool creator
 * Description: Creates a pg pool when only connection credentials are supplied in config.
 * Global Variables: none
 * @param options Connector options.
 * @returns Pool plus ownership flag.
 */
const createManagedPool = async (
    options: PgConnectorOptions
): Promise<{ pool: PgPoolLike; owned: boolean; }> => {
    if (options.pool) {
        return { pool: options.pool, owned: false };
    }

    if (options.client || options.executor) {
        return {
            pool: {
                query: async (statement, params) => {
                    if (typeof options.executor === "function") {
                        return options.executor(statement, params ?? []);
                    }

                    if (typeof options.client?.query === "function") {
                        return options.client.query(statement, params);
                    }

                    if (typeof options.client?.execute === "function") {
                        return options.client.execute(statement, params);
                    }

                    throw new Error("PostgreSQL client does not expose query or execute");
                }
            },
            owned: false
        };
    }

    const loadPgModule = new Function(
        "return import('pg')"
    ) as () => Promise<{ Pool: new (config: Record<string, unknown>) => PgPoolLike; }>;
    const pgModule = await loadPgModule();
    const pool = new pgModule.Pool({
        host: typeof options.host === "string" ? options.host : options.hostname,
        user: typeof options.user === "string" ? options.user : options.username,
        password: options.password,
        database: typeof options.database === "string" ? options.database : undefined,
        port: typeof options.port === "number" ? options.port : 5432,
        ssl: options.ssl as Record<string, unknown> | boolean | undefined,
        max: typeof options.max === "number" ? options.max : undefined,
        connectionString: typeof options.connectionString === "string" ? options.connectionString : undefined
    });

    return { pool, owned: true };
};

/**
 * Title: PostgreSQL connector factory
 * Description: Creates the PostgreSQL JSON connector with dialect-specific placeholders and function mapping.
 * Global Variables: none
 * @param options Connector options.
 * @returns PostgreSQL connector instance.
 */
export const createConnector: DatabaseConnectorFactory = async (options) => {
    const pgOptions = options as PgConnectorOptions;
    const { pool, owned } = await createManagedPool(pgOptions);
    const connector = createSqlConnector(
        {
            kind: "pgsql",
            quoteIdentifier: (identifier: string) => `"${identifier.replace(/"/g, "\"\"")}"`,
            placeholder: (index: number) => `$${index}`,
            functions: {
                LEN: "LENGTH",
                NOW: "NOW",
                CURRENT_TIMESTAMP: "CURRENT_TIMESTAMP",
                CURRENT_DATE: "CURRENT_DATE",
                DATE_DIFF: "DATE_PART"
            },
            supportsReturning: true,
            supportsIfNotExistsIndex: true,
            supportsFetch: true,
            ilikeOperator: "ILIKE",
            autoIncrementKeyword: "GENERATED BY DEFAULT AS IDENTITY"
        },
        {
            ...pgOptions,
            pool: {
                query: (statement, params) => pool.query(statement, params)
            }
        }
    );
    return {
        ...connector,
        async disconnect() {
            await connector.disconnect?.();
            if (owned && typeof pool.end === "function") {
                await pool.end();
            }
        },
        getNativeConnection() {
            return pool;
        }
    };
};

export default createConnector;
