import managerModule from "@zeruxjs/db";
import * as managerExports from "@zeruxjs/db";
export default managerModule;
export const db = managerExports["db"];
export const query = managerExports["query"];
export const createDb = managerExports["createDb"];
export const dropDb = managerExports["dropDb"];
export const switchDB = managerExports["switchDB"];
export const createTable = managerExports["createTable"];
export const dropTable = managerExports["dropTable"];
export const alterTable = managerExports["alterTable"];
export const turcunateTable = managerExports["turcunateTable"];
export const createIndex = managerExports["createIndex"];
export const dropIndex = managerExports["dropIndex"];
export const insert = managerExports["insert"];
export const select = managerExports["select"];
export const update = managerExports["update"];
const __zerux_delete = managerExports["delete"];
export { __zerux_delete as delete };
export const dbAccess = managerExports["dbAccess"];