import type * as DatabaseModule from "@zeruxjs/db";
declare const db: typeof import("@zeruxjs/db").default;
export default db;
export const db: typeof DatabaseModule["db"];
export const query: typeof DatabaseModule["query"];
export const createDb: typeof DatabaseModule["createDb"];
export const dropDb: typeof DatabaseModule["dropDb"];
export const switchDB: typeof DatabaseModule["switchDB"];
export const createTable: typeof DatabaseModule["createTable"];
export const dropTable: typeof DatabaseModule["dropTable"];
export const alterTable: typeof DatabaseModule["alterTable"];
export const turcunateTable: typeof DatabaseModule["turcunateTable"];
export const createIndex: typeof DatabaseModule["createIndex"];
export const dropIndex: typeof DatabaseModule["dropIndex"];
export const insert: typeof DatabaseModule["insert"];
export const select: typeof DatabaseModule["select"];
export const update: typeof DatabaseModule["update"];
declare const __zerux_delete: typeof DatabaseModule["delete"];
export { __zerux_delete as delete };
export const dbAccess: typeof DatabaseModule["dbAccess"];