import type { DatabaseFacade } from "@zeruxjs/db";
declare const db: DatabaseFacade;
export default db;
export { db };
export const slug: DatabaseFacade["slug"];
export const name: DatabaseFacade["name"];
export const connector: DatabaseFacade["connector"];
export const options: DatabaseFacade["options"];
export const query: DatabaseFacade["query"];
export const createDb: DatabaseFacade["createDb"];
export const dropDb: DatabaseFacade["dropDb"];
export const switchDB: DatabaseFacade["switchDB"];
export const createTable: DatabaseFacade["createTable"];
export const dropTable: DatabaseFacade["dropTable"];
export const alterTable: DatabaseFacade["alterTable"];
export const turcunateTable: DatabaseFacade["turcunateTable"];
export const createIndex: DatabaseFacade["createIndex"];
export const dropIndex: DatabaseFacade["dropIndex"];
export const insert: DatabaseFacade["insert"];
export const select: DatabaseFacade["select"];
export const update: DatabaseFacade["update"];
declare const __zerux_delete: DatabaseFacade["delete"];
export { __zerux_delete as delete };
export const native: DatabaseFacade["native"];