import { getActiveDatabaseManager } from "@zeruxjs/db";
const db = getActiveDatabaseManager().getConnectionFacade("something");
export default db;
export { db };
export const slug = db["slug"];
export const name = db["name"];
export const connector = db["connector"];
export const options = db["options"];
export const query = db["query"];
export const createDb = db["createDb"];
export const dropDb = db["dropDb"];
export const switchDB = db["switchDB"];
export const createTable = db["createTable"];
export const dropTable = db["dropTable"];
export const alterTable = db["alterTable"];
export const turcunateTable = db["turcunateTable"];
export const createIndex = db["createIndex"];
export const dropIndex = db["dropIndex"];
export const insert = db["insert"];
export const select = db["select"];
export const update = db["update"];
const __zerux_delete = db["delete"];
export { __zerux_delete as delete };
export const native = db["native"];